@url = http://localhost:3000/

# Raiz del api
# GET {{url}}

# Registro
#  @name registro
POST {{url}}/auth/registro
content-type: application/json
{
    "nombre": "David",
    "correo": "david.raw172@gmail.com",
    "contrasena": "uwu",
    "rol": "admin"
}

